version: "3"

services:
  transaction-bff:
    image: transaction-bff
    build: ./bff
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    expose:
      - 8080
      
  transaction-worker:
    image: transaction-worker
    build: ./worker
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
      - local-mongodb
    expose:
      - 8080

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    network_mode: bridge

  local-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    network_mode: bridge
    
volumes:
  cache:
    driver: local

